### ISSUE TITLE
Feature: Migrations require up/down methods instead of change when not automatically-reversible

### ISSUE THREAD

**Issue by TSMMark** [rubocop/rubocop-sequel#30]
A migration file that uses migration methods like `set_column_type`, or other non-reversible ones mentioned here https://sequel.jeremyevans.net/rdoc/files/doc/migration_rdoc.html#label-A+Basic+Migration is not reversible automatically, and should require specific up/down methods in migrations in projects where reversibility is important. I imagine a rubocop rule could check for this. 

Curious if maintainers would merge a PR that adds a new cop for this?

**Comment by cyberdelia** [comment]
Most likely we would accept something like that.

**Comment by cyberdelia** [comment]
This is now available in 0.3.5.
