### ISSUE TITLE
`IrreversibleMigration` too strict? Using almost any method causes an offense even when the migration is reversible 

### ISSUE THREAD

**Issue by dentarg** [rubocop/rubocop-sequel#48]
Silly example but

```ruby
Sequel.migration do
  change do
    alter_table :cars do
      add_column 'foo' + 'bar', :text
    end
  end
end
```

```shell
$ bundle e rubocop --only Sequel/IrreversibleMigration migrations/003_test.rb
Inspecting 1 file
C

Offenses:

migrations/003_test.rb:6:24: C: Sequel/IrreversibleMigration: Avoid using "+" inside a "change" block. Use "up" & "down" blocks instead.
      add_column 'foo' + 'bar', :text
                       ^

1 file inspected, 1 offense detected
```

I assume [the docs](https://sequel.jeremyevans.net/rdoc/files/doc/migration_rdoc.html#label-A+Basic+Migration), that say this

> The change block can usually correctly reverse the following methods: ...

means that there are _migration methods_ in Sequel that isn't reversible, and it is those this cop wants to catch. Here's a recent example where one such method was made reversible https://github.com/jeremyevans/sequel/pull/2060

**Comment by AlasdairWallaceMackie** [comment]
Thanks for the heads up! The PR I just created should fix this issue.

**Comment by AlasdairWallaceMackie** [comment]
@cyberdelia I think the repo release needs a version bump and this issue can be closed out.
